#!/usr/bin/env python3
"""
gRPC Servicer for Webcollector

Auto-generated by doc2db-integrate v2 (Phase 10).
Implements the WebcollectorService with 0 RPC handler(s).

Usage:
    python webcollector_servicer.py
"""
import os
import subprocess
from concurrent import futures
from pathlib import Path

import grpc

# These are generated by protoc from webcollector.proto
import webcollector_pb2
import webcollector_pb2_grpc

APP_DIR = Path(__file__).parent
DEFAULT_PORT = 50051


class WebcollectorServicer(webcollector_pb2_grpc.WebcollectorServiceServicer):
    """Implements the WebcollectorService gRPC interface."""

    def Health(self, request, context):
        """Health check."""
        return webcollector_pb2.HealthResponse(
            status="ok",
            app_id="webcollector",
        )


def serve(port: int = DEFAULT_PORT):
    """Start the gRPC server."""
    server = grpc.server(futures.ThreadPoolExecutor(max_workers=4))
    webcollector_pb2_grpc.add_WebcollectorServiceServicer_to_server(
        WebcollectorServicer(), server
    )
    server.add_insecure_port(f"[::]:{{port}}")
    server.start()
    print(f"gRPC server for Webcollector listening on port {{port}}")
    server.wait_for_termination()


if __name__ == "__main__":
    serve()
